### ISSUE TITLE
[responsive2] Sticky thead indicator

### ISSUE THREAD

**Issue by gedex** [kawalpemilu/kawalpemilu2019-www#10]
Saat sticky thead aktif dan scrolling berada pada baris berlatar belakang putih, sulit membedakan klo thead itu bukan termasuk row. Penambahan border atau shadow bisa membantu, misal:

<img width="652" alt="Screen Shot 2019-05-08 at 01 50 27" src="https://user-images.githubusercontent.com/78313/57325178-aced1480-7133-11e9-9ec0-42aeb516e0a3.png">

**Comment by fajran** [comment]
done f69aa9b
